automation:
  - alias: start pending to trigger away alarm
    trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: 'armed_away'
      to: 'pending'
    action:
    - service: media_player.turn_on
      entity_id: media_player.living_room_speaker
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'The Alarm is armed.  Please disarm the alarm!'