dist: bionic
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_google_service_account.json google_service_account.json
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
