homeassistant:
  # Name of the location where Home Assistant is running
  name: Masarn Goch
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 195
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  packages: !include_dir_named packages
    
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

scene: !include scenes.yaml

automation: !include automations.yaml

updater:

discovery:

history:

map:

sun:

person:

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 25
    icon: mdi:home

  - name: Emma's School
    latitude: !secret emma_school_latitude
    longitude: !secret emma_school_longitude
    radius: 40
    icon: mdi:school

  - name: Nia's House
    latitude: !secret nia_latitude
    longitude: !secret nia_longitude
    radius: 40
    icon: mdi:home-map-marker
  
  - name: Agatha's House
    latitude: !secret agatha_latitude
    longitude: !secret agatha_longitude
    radius: 40
    icon: mdi:home-map-marker