anniversaries:
  sensors:
  - name: Jo's Birthday
    date: !secret jo_birthday

automation:
- alias: Jo's Birthday Greeting
  trigger:
    platform: time
    at: "15:50:00"
  condition:
    - condition: state
      entity_id: sensor.anniversary_jo_s_birthday
      state:  '0'
  action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: "Happy Birthday To Jo!"
        data:
          tag: birthday
    - service: notify.broadcast_from_home_assistant
      data:
        message: "Happy Birthday Jo!"