sensor:
  - platform: template
    sensors:
      accuweather_template_temperature:
        value_template: '{{ state_attr("weather.accuweather","temperature")}}'
      accuweather_template_humidity:
        value_template: '{{ state_attr("weather.accuweather","humidity")}}'
      accuweather_template_ozone:
        value_template: '{{ state_attr("weather.accuweather","ozone")}}'
      accuweather_template_uv_level:
        value_template: '{{ state_attr("sensor.accuweather_uv_index","level")}}'
      accuweather_template_pressure:
        value_template: '{{ state_attr("weather.accuweather","pressure")}}'
      accuweather_template_visibility:
        value_template: '{{ state_attr("weather.accuweather","visibility")}}'
      accuweather_template_wind_bearing:
        value_template: '{{ state_attr("weather.accuweather","wind_bearing")}}'
      accuweather_template_wind_speed:
        value_template: '{{ state_attr("weather.accuweather","wind_speed")}}'
      accuweather_template_icons_day1:
        value_template: '{{ state_attr("weather.accuweather","forecast")[0].condition }}'
      accuweather_template_icons_day2:
        value_template: '{{ state_attr("weather.accuweather","forecast")[1].condition }}'
      accuweather_template_icons_day3:
        value_template: '{{ state_attr("weather.accuweather","forecast")[2].condition }}'
      accuweather_template_icons_day4:
        value_template: '{{ state_attr("weather.accuweather","forecast")[3].condition }}'
      accuweather_template_icons_day5:
        value_template: '{{ state_attr("weather.accuweather","forecast")[4].condition }}'
      accuweather_template_temphigh_day1:
        value_template: '{{ state_attr("weather.accuweather","forecast")[0].temperature }}'
      accuweather_template_temphigh_day2:
        value_template: '{{ state_attr("weather.accuweather","forecast")[1].temperature }}'
      accuweather_template_temphigh_day3:
        value_template: '{{ state_attr("weather.accuweather","forecast")[2].temperature }}'
      accuweather_template_temphigh_day4:
        value_template: '{{ state_attr("weather.accuweather","forecast")[3].temperature }}'
      accuweather_template_temphigh_day5:
        value_template: '{{ state_attr("weather.accuweather","forecast")[4].temperature }}'
      accuweather_template_templow_day1:
        value_template: '{{ state_attr("weather.accuweather","forecast")[0].templow }}'
      accuweather_template_templow_day2:
        value_template: '{{ state_attr("weather.accuweather","forecast")[1].templow }}'
      accuweather_template_templow_day3:
        value_template: '{{ state_attr("weather.accuweather","forecast")[2].templow }}'
      accuweather_template_templow_day4:
        value_template: '{{ state_attr("weather.accuweather","forecast")[3].templow }}'
      accuweather_template_templow_day5:
        value_template: '{{ state_attr("weather.accuweather","forecast")[4].templow }}'
      accuweather_template_precipitation_probability_day1:
        value_template: '{{ state_attr("weather.accuweather","forecast")[0].precipitation_probability }}'
      accuweather_template_precipitation_probability_day2:
        value_template: '{{ state_attr("weather.accuweather","forecast")[1].precipitation_probability }}'
      accuweather_template_precipitation_probability_day3:
        value_template: '{{ state_attr("weather.accuweather","forecast")[2].precipitation_probability }}'
      accuweather_template_precipitation_probability_day4:
        value_template: '{{ state_attr("weather.accuweather","forecast")[3].precipitation_probability }}'
      accuweather_template_precipitation_probability_day5:
        value_template: '{{ state_attr("weather.accuweather","forecast")[4].precipitation_probability }}'
      accuweather_template_precipitation_day1:
        value_template: '{{ state_attr("weather.accuweather","forecast")[0].precipitation }}'
      accuweather_template_precipitation_day2:
        value_template: '{{ state_attr("weather.accuweather","forecast")[1].precipitation }}'
      accuweather_template_precipitation_day3:
        value_template: '{{ state_attr("weather.accuweather","forecast")[2].precipitation }}'
      accuweather_template_precipitation_day4:
        value_template: '{{ state_attr("weather.accuweather","forecast")[3].precipitation }}'
      accuweather_template_precipitation_day5:
        value_template: '{{ state_attr("weather.accuweather","forecast")[4].precipitation }}'
