#
#  These automations give warnings of nearby lightning strikes.
#  The information on lightning strikes comes from the
#  custom component Blizortung (installed via HACS).
#  It is configured on the Integrations page
#  The additional template sensor is used to convert distance 
#  to miles instead of km
#

sensor:
  - platform: template
    sensors:
      lightning_distance_miles:
        entity_id: sensor.lightning_distance
        friendly_name: "Lightning Distance"
        unit_of_measurement: 'miles'
        value_template: >
          {% if is_state("sensor.lightning_distance","unknown") -%}
            Unknown
          {% else -%}
            {{ (states("sensor.lightning_distance") |float * 0.621371 )| int}}
          {% endif %}

automation:
  - id: "0acb2859-1630-4a1a-88c4-31142991b041"
    alias: Lightning warning
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightning_distance_miles
        above: 20
    action:
      - service: notify.broadcast_from_home_assistant
        data_template:
          message: 'Warning.  Lightning detected at {{states("sensor.lightning_distance_miles")}} miles'
      - service: notify.mobile_app_jenny_s_oppo_reno
        data_template:
          message: 'Lightning detected at {{states("sensor.lightning_distance_miles")}} miles'
          title: Lightning warning
          data:
            group: weather
            tag: lightning
            color: '#ffff00'
            timeout: 600
      - delay:
          minutes: 120

  - id: "45af121b-63cb-4e55-99d5-63c8fabe2500"
    alias: Lightning Close Warning
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightning_distance_miles
        below: 20
        above: 5
    action:
      - service: notify.broadcast_from_home_assistant
        data_template:
          message: 'Warning.  Lightning detected at {{states("sensor.lightning_distance_miles")}} miles'
      - service: notify.mobile_app_jenny_s_oppo_reno
        data_template:
          message: 'Lightning detected at {{states("sensor.lightning_distance_miles")}} miles'
          title: Lightning warning
          data:
            group: weather
            tag: lightning
            color: '#ffff00'
            timeout: 600
      - delay:
          minutes: 120

  - id: "b304f5fc-3e71-4b79-851b-c7289b91aa21"
    alias: Lightning VERY Close Warning
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.lightning_distance_miles
        below: 5
    action:
      - service: notify.broadcast_from_home_assistant
        data_template:
          message: 'Warning.  Lightning detected at {{states("sensor.lightning_distance_miles")}} miles'
      - service: notify.mobile_app_jenny_s_oppo_reno
        data_template:
          message: 'Lightning detected at {{states("sensor.lightning_distance_miles")}} miles'
          title: Lightning warning
          data:
            group: weather
            tag: lightning
            color: '#ffff00'
            timeout: 600
      - delay:
          minutes: 120