automation:
  - alias: Night - Downstairs lights off at 1am
    trigger:
    - at: 01:00
      platform: time
    condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
    action:
    - service: light.turn_off
      entity_id: light.downstairs_lights