automation:
  - alias: Emma left house
    trigger:
    - entity_id: person.emma_gorton
      platform: state
      from: Home
    action:
    - data:
        message: Emma has left the house
        data:
          tag: emma_location
          renotify: 1
          priority: high
      service: notify.html