automation:
  - alias: Emma at Agatha's
    trigger:
      - platform: zone
        entity_id: person.emma_gorton
        zone: zone.agatha_s_house
        event: enter
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        message: Emma has arrived at Agatha's
        data:
          tag: emma_location
  
  - alias: Emma left Agatha's
    trigger:
      - platform: zone
        entity_id: person.emma_gorton
        zone: zone.agatha_s_house
        event: leave
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        title: Emma Location
        message: Emma has Left Agatha's House
        data:
          tag: emma_location