sensor:
  platform: template
  sensors:
    emma_tracker:
      friendly_name: "Emma"
      value_template: >
        {% if is_state('device_tracker.Emma_Wifi','home') or is_state('device_tracker.emma_bt','home') or is_state('device_tracker.emma_gps','home') %}
          Home
        {% else %}
          {{ states('sensor.emma_location') }}
        {% endif %}