automation:
  - alias: Emma home
    trigger:
    - platform: state
      entity_id: person.emma_gorton
      to: Home
    action:
    - service: notify.html
      data:
        message: Emma has arrived home
        data:
          tag: emma_location
          renotify: 1
          priority: high
    - service: notify.broadcast
      data:
        message: 'Emma is home!'