sensor:
  - platform: template
    sensors:
      emma_location:
        entity_id:
          - person.emma_gorton
          - sensor.emmas_phone_geocoded_location
        value_template: >-
          {% if is_state("person.emma_gorton", "not_home") -%}
            {{ states("sensor.emmas_phone_geocoded_location") }}
          {%- else -%}
            {{ states("person.emma_gorton") }}
          {%- endif %}