automation:
  - alias: Emma home
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.home
      event: enter
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        title: Emma Location
        message: Emma has arrived home
        data:
          tag: emma_location
    - service: notify.broadcast
      data:
        message: 'Emma is home!'

  - alias: Emma left home
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.home
      event: leave
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        title: Emma Location
        message: Emma has Left The House
        data:
          tag: emma_location
    - service: notify.broadcast
      data:
        message: 'Emma has Left The House!'