automation:
  - alias: Emma at Nia's
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.nia_s_house
      event: enter
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: Emma has arrived at Nia's
        title: Emma Location
        data:
          tag: emma_location

  - alias: Emma left Nia's
    trigger:
    - platform: zone
      entity_id: person.emma_gorton
      zone: zone.nia_s_house
      event: leave
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: Emma has Left Nia's
        title: Emma Location
        data:
          tag: emma_location