camera:
  - platform: generic
    name: ChickenCam
    still_image_url: !secret chickencam_still_url
    stream_source: !secret chickencam_stream_url
    verify_ssl: false
    username: !secret chickencam_user
    password: !secret chickencam_password

switch:
  - platform: template
    switches:
      chickencam_motion_detection:
        turn_on:
          service: rest_command.chickencam_start_detection
        turn_off:
          service: rest_command.chickencam_pause_detection

binary_sensor:
  - platform: mqtt
    name: chickencam
    state_topic: "cameras/chickencam/motion"
    device_class: motion

rest_command:
  chickencam_start_detection:
    url: !secret chickencam_start_detection_url
  chickencam_pause_detection:
    url: !secret chickencam_pause_detection_url
