sensor:
  - platform: template
    sensors:
      jenny_location:
        value_template: >-
          {% if is_state("person.jenny_gorton", "not_home") -%}
            {{ states("sensor.jenny_s_oppo_reno_geocoded_location") }}
          {%- else -%}
            {{ states("person.jenny_gorton") }}
          {%- endif %}