automation:
  - alias: Jenny home
    trigger:
    - platform: zone
      entity_id: person.jenny_gorton
      zone: zone.home
      event: enter
    action:
    - service: notify.broadcast
      data:
        message: 'Jenny is home!'