automation:
  - alias: Jenny home
    trigger:
    - entity_id: person.jenny_gorton
      to: home
      platform: state
    action:
    - service: notify.broadcast
      data:
        message: 'Jenny is home!'