sensor:
  platform: template
  sensors:
    jenny_tracker:
      friendly_name: "Jenny"
      value_template: >
        {% if is_state('device_tracker.Jenny_Wifi','home') or is_state('device_tracker.jenny_bt','home') or is_state('device_tracker.jenny_gps','home') %}
          Home
        {% else %}
          {{ states('sensor.jenny_location') }}
        {% endif %}