sensor:
  - platform: template
    sensors:
      jenny_location:
        value_template: >-
          {% if is_state("device_tracker.jenny_s_oppo_reno", "not_home") -%}
            {{ states("sensor.jenny_s_oppo_reno_geocoded_location") }}
          {%- else -%}
            {{ states("device_tracker.jenny_s_oppo_reno") }}
          {%- endif %}