automation:
  - alias: door and window battery warnings
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.bedroom_window_battery
          - binary_sensor.door_window_battery
          - binary_sensor.emma_s_window_battery
          - binary_sensor.freezer_door_battery
          - binary_sensor.fridge_door_battery
          - binary_sensor.front_door_battery
          - binary_sensor.front_window_battery
          - binary_sensor.kitchen_window_battery
        to: 'on'
    action:
      - service: persistent_notification.create
        data_template:
          title: "Low Battery"
          message: >
            "Replace batteries: "
            {% if is_state("binary_sensor.bedroom_window_battery", "on") -%}
              \n Bedroom Window
            {%- endif %}
            {% if is_state("binary_sensor.door_window_battery", "on") -%}
              \n Door Window
            {%- endif %}
            {% if is_state("binary_sensor.emma_s_window_battery", "on") -%}
              \n Emma's Window
            {%- endif %}
            {% if is_state("binary_sensor.freezer_door_battery", "on") -%}
              \n Freezer Door
            {%- endif %}
            {% if is_state("binary_sensor.fridge_door_battery", "on") -%}
              \n Fridge Door
            {%- endif %}
            {% if is_state("binary_sensor.front_door_battery", "on") -%}
              \n Front Door
            {%- endif %}
            {% if is_state("binary_sensor.front_window_battery", "on") -%}
              \n Front Window
            {%- endif %}
            {% if is_state("binary_sensor.kitchen_window_battery", "on") -%}
              \n Kitchen Window
            {%- endif %}