sensor:
  - platform: youtube
    channel_id: UCGvWVUTM8wQ3AfMuS4rXbPQ
  
  - platform: socialblade
    name: diocese_of_wrexham_info
    channel_id: UCGvWVUTM8wQ3AfMuS4rXbPQ

automation:
  - alias: YouTube Notification - Diocese of Wrexham (TTS)
    trigger:
      - platform: state
        entity_id: sensor.diocese_of_wrexham
    condition:
      - condition: template
        value_template: '{{ is_state_attr("sensor.diocese_of_wrexham", "live", True) }}'
      - condition: template
        value_template: >-
          {{ as_timestamp(utcnow()) -
              as_timestamp(state_attr("automation.youtube_notification_diocese_of_wrexham_tts","last_triggered")) > 300 }}
    action:
      - service: notify.broadcast_from_home_assistant
        data_template:
          message:  >
            The diocese of Wrexham is live on youtube with 
            {{ states("sensor.diocese_of_wrexham")}}
