sensor:
  - platform: youtube
    channel_id: UC7G4tLa4Kt6A9e3hJ-HO8ng
  
  - platform: socialblade
    name: drzzs_info
    channel_id: UC7G4tLa4Kt6A9e3hJ-HO8ng

automation:
  - alias: YouTube Notification - DrZzs
    trigger:
      - platform: state
        entity_id: sensor.drzzs
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data_template:
        message: '{{ states("sensor.drzzs")}}'
        title: >
          {% if is_state_attr("sensor.drzzs", "live", False) -%}
          'New DrZzs Video Available'
          {%- else -%}
          'DrZzs is Live!'
          {%- endif %}
        data:
          image: "{{state_attr('sensor.drzzs','entity_picture')}}"
          tag: drzzs
          color: 'green'
          actions:
            - action: "URI"
              title: "Watch Now"
              uri: '{{ state_attr("sensor.drzzs","url") }}'