sensor:
  - platform: youtube
    channel_id: UCZ2Ku6wrhdYDHCaBzLaA3bw
  
  - platform: socialblade
    name: frenck_info
    channel_id: UCZ2Ku6wrhdYDHCaBzLaA3bw

automation:
  - alias: YouTube Notification - Frank Nijhof
    trigger:
      - platform: state
        entity_id: sensor.franck_nijhof
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data_template:
        message: '{{ states("sensor.franck_nijhof")}}'
        title: >
          {% if is_state_attr("sensor.drzzs", "live", False) -%}
          'New Franck Nijhof Video Available'
          {%- else -%}
          'Franck Nijhof is Live!'
          {%- endif %}
        data:
          image: "{{state_attr('sensor.franck_nijhof','entity_picture')}}"
          tag: franck_nijhof
          actions:
            - action: "URI"
              title: "Watch Now"
              uri: '{{ state_attr("sensor.franck_nijhof","url") }}'