sensor:
  - platform: youtube
    channel_id: UCx2xTsk2RnLHU-a139MOcmA
  
  - platform: socialblade
    name: kevinoilpainting_info
    channel_id: UCx2xTsk2RnLHU-a139MOcmA

automation:
  - alias: YouTube Notification - KevinOilPainting
    trigger:
      - platform: state
        entity_id: sensor.kevinoilpainting
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data_template:
        message: '{{ states("sensor.kevinoilpainting")}}'
        title: >
          {% if is_state_attr("sensor.kevinoilpainting", "live", False) -%}
          'New KevinOilPainting Video Available'
          {%- else -%}
          'KevinOilPainting is Live!'
          {%- endif %}
        data:
          image: "{{state_attr('sensor.kevinoilpainting','entity_picture')}}"
          tag: kevinoilpainting
          color: 'green'
          actions:
            - action: "URI"
              title: "Watch Now"
              uri: '{{ state_attr("sensor.kevinoilpainting","url") }}'