sensor:
  - platform: youtube
    channel_id: UC2gyzKcHbYfqoXA5xbyGXtQ
  
  - platform: socialblade
    name: the_hook_up_info
    channel_id: UC2gyzKcHbYfqoXA5xbyGXtQ

automation:
  - alias: YouTube Notification - The Hook Up
    trigger:
      - platform: state
        entity_id: sensor.the_hook_up
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data_template:
        message: '{{ states("sensor.the_hook_up")}}'
        title: >
          {% if is_state_attr("sensor.the_hook_up", "live", False) -%}
          'New The Hook Up Video Available'
          {%- else -%}
          'The Hook Up is Live!'
          {%- endif %}
        data:
          image: "{{state_attr('sensor.the_hook_up','entity_picture')}}"
          tag: the_hook_up
          color: 'green'
          actions:
            - action: "URI"
              title: "Watch Now"
              uri: '{{ state_attr("sensor.the_hook_up","url") }}'