esphome:
  name: jos_control_panel
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  reboot_timeout: 10min
  manual_ip:
    static_ip: 192.168.1.11
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

binary_sensor:
  - platform: gpio
    pin:
      number: 23
      mode: INPUT_PULLUP
      inverted: true
    name: "Jo's Green switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
  
  - platform: gpio
    pin:
      number: 22
      mode: INPUT_PULLUP
      inverted: true
    name: "Jo's Orange switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
      
  - platform: gpio
    pin:
      number: 21
      mode: INPUT_PULLUP
      inverted: true
    name: "Jo's Red switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    
  - platform: gpio
    pin:
      number: 19
      mode: INPUT_PULLUP
      inverted: true
    name: "Jo's Blue switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    
  - platform: gpio
    pin:
      number: 18
      mode: INPUT_PULLUP
      inverted: true
    name: "Jo's Purple switch"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
      
  - platform: status
    name: Jo's Control Panel Status
    
sensor:
  - platform: wifi_signal
    name: Jo's Control Panel Wifi Signal
    update_interval: 10s

  - platform: uptime
    name: Jo's Control Panel Uptime

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:C7:7D:64"
    bindkey: "d25787b647b14c66f5aceb95f1a33570"
    temperature:
      name: "Emma's Room Temperature"
    humidity:
      name: "Emma's Room Humidity"
    battery_level:
      name: "Emma's Room Temp Sensor Battery Level" 

  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:3E:41:7D"
    bindkey: "d25787b647b14c66f5aceb95f1a33570"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Temp Sensor Battery Level"

status_led:
  pin:
    number: 2
    inverted: true