substitutions:
  devicename: kitchen_socket_1
  friendly_name: Kitchen Socket 1
  ip_address: 192.168.1.50
  reboot_time: 0s

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/bseed_socket.yaml
