light:
  - platform: template
    lights:
      emma_night_light:
        friendly_name: "Emma's Night Light"
        value_template: "{{ is_state('light.emma_led', 'on') and
          is_state_attr('light.emma_led','effect','Solid Color') and 
          is_state_attr('light.emma_led','rgb_color',(255, 108, 145)) and
          is_state_attr('light.emma_led','brightness',15)}}"
        turn_on:
          - service: light.turn_on
            entity_id: light.emma_led
            data: 
              effect: "Solid Color"
              brightness: 15
              rgb_color: [255, 108, 145]
        turn_off:
          - condition: template
            value_template: "{{ is_state('light.emma_led', 'on') and
              is_state_attr('light.emma_led','effect','Solid Color') and 
              is_state_attr('light.emma_led','rgb_color',(255, 108, 145)) and
              is_state_attr('light.emma_led','brightness',15)}}"
          - service: mqtt.publish
            data: 
              topic: "cmnd/emma-led"
              payload: "{\"state\":\"OFF\",\"brightness\":150}"

automation:
  - alias: Emma's night light off 1 hour after sunrise
    trigger:
    - event: sunrise
      offset: '1:00'
      platform: sun
    action:
    - service: light.turn_off
      entity_id: light.emma_night_light