input_boolean:
  sunrise_for_emma_led:
    name: Sunrise for Emma's Den Lights

automation:
  - alias: Sunrise in emma's room for 8am
    trigger:
      platform: time
      at: "07:40:00"
    action:
      - service: light.turn_on
        entity_id: light.emma_led
        data:
          effect: "Sunrise"

  - alias: turn on sunrise input boolean for Emma_led
    trigger:
      platform: sun
      event: sunrise
      offset: "01:00:00"
    condition:
      - condition: template
        value_template: >
          {{ is_state_attr("light.emma_led","effect","Sunrise") or
          is_state_attr('light.emma_led','effect','Daylight') or
          is_state_attr('light.emma_led','effect','Night Light')}}
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.sunrise_for_emma_led

  - alias: Emma's Daylight mode off after sunrise
    trigger:
      - platform: state
        entity_id: input_boolean.sunrise_for_emma_led
      - platform: template
        value_template: >-
          {{ is_state_attr('light.emma_led','effect', 'Daylight') }}
    condition:
      - condition: template
        value_template: >-
          {{ is_state_attr("light.emma_led","effect","Daylight") and
          is_state('input_boolean.sunrise_for_emma_led') }}
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.sunrise_for_emma_led
      - service: light.turn_off
        entity_id: light.emma_led

  - alias: sunset in emma's room at sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"
    condition:
      - condition: template
        value_template: >-
          {{ is_state('light.emma_led','off') or
          is_state_attr('light.emma_led', 'effect', 'Daylight')}}
    action:
      service: light.turn_on
      entity_id: light.emma_led
      data:
        effect: "Sunset"

