input_boolean:
  sunrise_for_emma_led:
    name: Sunrise for Emma's Den Lights

automation:
  - alias: Sunrise in emma's room for 8am
    trigger:
      platform: time
      at: "07:40:00"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.sunrise_for_emma_led
      - service: light.turn_on
        entity_id: light.emma_led
        data:
          effect: "Sunrise"

  - alias: turn on sunrise input boolean for Emma_led
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      above: 4.0
      below: 5.0
    condition:
      - condition: state
        entity_id: automation.sunrise_in_emma_s_room_for_8am
        state: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.sunrise_for_emma_led

  - alias: Emma's Daylight mode off after sunrise
    trigger:
      - platform: template
        value_template: >
          {{ is_state_attr('light.emma_led','effect', 'Daylight') }}
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        above: 4.0
        below: 5.0
    condition:
      - condition: template
        value_template: >
          {{is_state('input_boolean.sunrise_for_emma_led') and
          state_attr('sun.sun', 'elevation') > 4 }}
    action:
      - condition: template
        value_template: >
          {{ not is_state_attr("light.emma_led","effect","Night Light") and
          not is_state_attr("light.emma_led","effect","Sunrise") and
          state_attr("light.emma_led","effect") != None }}
      - service: input_boolean.turn_off
        entity_id: input_boolean.sunrise_for_emma_led
      - condition: template
        value_template: >
          {{ is_state_attr('light.emma_led','effect', 'Daylight') }}
      - service: light.turn_off
        entity_id: light.emma_led

  - alias: sunset in emma's room at sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"
    condition:
      - condition: template
        value_template: >-
          {{ is_state('light.emma_led','off') or
          is_state_attr('light.emma_led', 'effect', 'Daylight')}}
    action:
      service: light.turn_on
      entity_id: light.emma_led
      data:
        effect: "Sunset"

