automation:
  - alias: Home Assistant Update Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        to: 'on'
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        message: Home Assistant version {{ state_attr("binary_sensor.updater","newest_version") }} available
        title: Update Home Assistant
        data:
          sticky: 'true'
          tag: update_ha
          color: '#ff8c00'
          clickAction: /hassio/dashboard
    - service: persistent_notification.create
      data_template:
        title: Update Home Assistant
        message: >-
          There is a Home Assistant upgrade available!
          Version {{ state_attr("binary_sensor.updater","newest_version") }} has been released!
        notification_id: update_ha

  - alias: Home Assistant Update Notification Dismiss
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        to: 'off'
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        message: clear_notification
        data:
          tag: update_ha
    - service: persistent_notification.dismiss
      data:
        notification_id: update_ha