hacs:
  token: !secret hacs_github_token
  sidepanel_title: HACS
  sidepanel_icon: hacs:hacs

automation:
  - id: 'd73b2704-f6e5-42dc-9dfd-0c43a4853c05'
    alias: HACS Component Update Notification
    trigger:
      - platform: state
        entity_id: sensor.hacs
    condition:
      - condition: numeric_state
        entity_id: sensor.hacs
        above: 0
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: >
          There are updates to {{ states("sensor.hacs") }} HACS components:
          {% for repo in state_attr("sensor.hacs","repositories") %}
            * {{repo['display_name'] }} {{ repo['installed_version'] }} -> {{ repo['available_version'] }}
          {%- endfor %}
        title: HACS Components Updates Available
        data:
          sticky: 'true'
          tag: update_hacs
          group: updates
          color: '#ff8c00'
          clickAction: /hacs/installed
    - service: persistent_notification.create
      data_template:
        title: Update Home Assistant
        message: >-
          There are updates to {{ states("sensor.hacs") }} HACS components:
          {% for repo in state_attr("sensor.hacs","repositories") %}
            * **{{repo['display_name'] }}** _{{ repo['installed_version'] }}_ -> _{{ repo['available_version'] }}_
          {%- endfor %}
        notification_id: update_hacs

  - id: 'f72cfd6c-954f-42d6-9e01-d421f816ee14'
    alias: HACS Component Update Notification Dismiss
    trigger:
      - platform: state
        entity_id: sensor.hacs
        to: '0'
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: clear_notification
        data:
          tag: update_hacs
    - service: persistent_notification.dismiss
      data:
        notification_id: update_hacs