hacs:
  token: !secret github_token
  sidepanel_title: HACS
  sidepanel_icon: hacs:hacs

automation:
  - alias: HACS Component Update Notification
    trigger:
      - platform: state
        entity_id: sensor.hacs
    condition:
      - condition: numeric_state
        entity_id: sensor.hacs
        above: 0
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        message: >
          There are updates to {{ states("sensor.hacs") }} HACS components:
          {% for repo in state_attr("sensor.hacs","repositories") %}
            * {{repo['display_name'] }} {{ repo['installed version'] }} -> {{ repo['available version'] }}
          {%- endfor %}
        title: HACS Components Updates Available
        data:
          sticky: 'true'
          tag: update_hacs
          color: '#ff8c00'
          clickAction: /hacs/installed
    - service: persistent_notification.create
      data_template:
        title: Update Home Assistant
        message: >-
          There are updates to {{ states("sensor.hacs") }} HACS components:
          {% for repo in state_attr("sensor.hacs","repositories") %}
            * **{{repo['display_name'] }}** _{{ repo['installed version'] }}_ -> _{{ repo['available version'] }}_
          {%- endfor %}
        notification_id: update_hacs

  - alias: HACS Component Update Notification Dismiss
    trigger:
      - platform: state
        entity_id: sensor.hacs
        to: '0'
    action:
    - service: notify.mobile_app_jenny_s_blackberry_motion
      data:
        message: clear_notification
        data:
          tag: update_hacs
    - service: persistent_notification.dismiss
      data:
        notification_id: update_hacs