sensor: 
  - platform: version
    name: homeassistant_version_available
    source: hassio
    image: qemux86-64

  - platform: version
    name: homeassistant_current_version

input_text:
  ha_version_notified:
    name: Home assistant update version notified

automation:
  - id: 'cf6506cb-87e3-4dcd-ae33-3d93fa04d140'
    alias: Home Assistant Update Notification
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sensor.homeassistant_version_available
    condition:
      - condition: template
        value_template: >
          {{
          states("sensor.homeassistant_version_available") != states("sensor.homeassistant_current_version")
          and states("sensor.homeassistant_version_available") != "unknown"
          and states("sensor.homeassistant_version_available") != states("input_text.ha_version_notified")
          }}
    action:
    - service: input_text.set_value
      data:
        entity_id: input_text.ha_version_notified
        value: '{{ states("sensor.homeassistant_version_available") }}'
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
            Triggering Travis build...
        title: Update Home Assistant
        data:
          sticky: 'true'
          group: updates
          tag: update_ha
          color: '#ff8c00'
          clickAction: /hassio/dashboard
    - service: persistent_notification.create
      data:
        title: Update Home Assistant
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
            Triggering Travis build...
        notification_id: update_ha
    - service: rest_command.github_issue_state
      data:
        issue: 11
        status: "open"
    - service: rest_command.github_issue_comment
      data:
        issue: '11'
        message: ' Home Assistant version {{ states("sensor.homeassistant_version_available") }} is now available"}'
    - service: rest_command.travis_build
    # wait for travis build to start then update notification
    - wait_template: "{{ is_state('sensor.travis_ci_home_assistant_config', 'started') }}"
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
            Travis Build has started
        title: Update Home Assistant
        data:
          sticky: 'true'
          group: updates
          tag: update_ha
          color: '#ff8c00'
          clickAction: /hassio/dashboard
    - service: persistent_notification.create
      data:
        title: Update Home Assistant
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
            Travis Build has started
        notification_id: update_ha
    # wait for build to complete and update notification with status
    - wait_template: "{{ not is_state('sensor.travis_ci_home_assistant_config', 'created') and not is_state('sensor.travis_ci_home_assistant_config', 'started') }}"
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
            Travis Build has {{states('sensor.travis_ci_home_assistant_config')}}
        title: Update Home Assistant
        data:
          group: updates
          sticky: 'true'
          tag: update_ha
          color: '#ff8c00'
          clickAction: /hassio/dashboard
    - service: persistent_notification.create
      data:
        title: Update Home Assistant
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
            Travis Build has {{states('sensor.travis_ci_home_assistant_config')}}
        notification_id: update_ha
    - service: rest_command.github_issue_comment
      data:
        issue: '11'
        message: "Travis build has {{ states('sensor.travis_ci_home_assistant_config') }}"

  - id: '7e81d1d4-9fb7-47d1-89d1-2e8624673f3d'
    alias: Home Assistant Update Notification Dismiss
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id:
          - sensor.homeassistant_version_available
          - sensor.homeassistant_current_version
    condition:
      - condition: template
        value_template: >
          {{ states("sensor.homeassistant_version_available") != "unavailable" and
          states("sensor.homeassistant_version_available") == states("sensor.homeassistant_current_version") }}
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: clear_notification
        data:
          tag: update_ha
    - service: persistent_notification.dismiss
      data:
        notification_id: update_ha
    - service: rest_command.github_issue_state
      data:
        issue: '11'
        status: "closed"