sensor:
  - platform: command_line
    name: HassOS Current Version
    command: 'curl http://supervisor/host/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" '
    value_template: "{{ value_json.data.operating_system[7:] }}"
    json_attributes:
    - data

automation:
  - alias: OS Update Notification
    trigger:
      - platform: state
        entity_id: sensor.homeassistant_version_available
      - platform: homeassistant
        event: start
    condition:
      - condition: template
        value_template: '{{ states("sensor.hassos_current_version") != state_attr("sensor.homeassistant_version_available", "hassos") }}'
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: >
          There is an update to Home Assistant OS:
            * {{ states("sensor.hassos_current_version") }} -> {{ state_attr("sensor.homeassistant_version_available", "hassos") }}
        title: OS Update Available
        data:
          sticky: 'true'
          tag: update_os
          color: '#ff8c00'
          clickAction: /hasio/dashboard
    - service: persistent_notification.create
      data_template:
        title: OS Update Available
        message: >-
          There is an update to Home Assistant OS:
            * {{ states("sensor.hassos_current_version") }} -> {{ state_attr("sensor.homeassistant_version_available", "hassos") }}
        notification_id: update_os

  - alias: OS Update Notification Dismiss
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id:
          - sensor.homeassistant_version_available
          - sensor.hassos_current_version
    condition:
      - condition: template
        value_template: '{{ states("sensor.hassos_current_version") == state_attr("sensor.homeassistant_version_available", "hassos") }}'
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: clear_notification
        data:
          tag: update_os
    - service: persistent_notification.dismiss
      data:
        notification_id: update_os