sensor: 
  - platform: version
    name: homeassistant_version_available
    source: hassio
    image: qemux86-64

  - platform: version
    name: homeassistant_current_version

automation:
  - id: 'cf6506cb-87e3-4dcd-ae33-3d93fa04d140'
    alias: Home Assistant Update Notification
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sensor.homeassistant_version_available
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.homeassistant_version_available
            state: "unknown"
      - condition: template
        value_template: '{{ states("sensor.homeassistant_version_available") != states("sensor.homeassistant_current_version") }}'
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
        title: Update Home Assistant
        data:
          sticky: 'true'
          tag: update_ha
          color: '#ff8c00'
          clickAction: /hassio/dashboard
    - service: persistent_notification.create
      data_template:
        title: Update Home Assistant
        message: >
          There is an update to Home Assistant core
            * {{ states("sensor.homeassistant_current_version") }} -> {{ states("sensor.homeassistant_version_available") }}
        notification_id: update_ha
    - service: rest_command.new_version_github_issue
      data_template:
        status: "open"
    - service: rest_command.new_version_github_issue_comment
      data_template:
        version: '{{ states("sensor.homeassistant_version_available") }}'

  - id: '7e81d1d4-9fb7-47d1-89d1-2e8624673f3d'
    alias: Home Assistant Update Notification Dismiss
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id:
          - sensor.homeassistant_version_available
          - sensor.homeassistant_current_version
    condition:
      - condition: template
        value_template: '{{ states("sensor.homeassistant_version_available") == states("sensor.homeassistant_current_version") }}'
    action:
    - service: notify.mobile_app_jenny_s_oppo_reno
      data:
        message: clear_notification
        data:
          tag: update_ha
    - service: persistent_notification.dismiss
      data:
        notification_id: update_ha

rest_command:
  new_version_github_issue:
    url: "https://api.github.com/repos/pinkywafer/Home-Assistant_Config/issues/11"
    method: PATCH
    headers:
      Authorization: !secret github_issue_token
    payload: '{"state":"{{ status }}"}'

  new_version_github_issue_comment:
    url: 'https://api.github.com/repos/pinkywafer/Home-Assistant_Config/issues/11/comments'
    method: POST
    headers:
      Authorization: !secret github_issue_token
    payload: '{ "body": "Home Assistant version {{ version }} is now available"}'